name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: "x86_64"
    - name: Set up rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rust-src
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
