name: Docker tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ruinos/alpine-tests:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
